### PR TITLE
Adding reproduction_command to the tracker driver.

### PR DESCRIPTION
**Pull request by cpatrick**

### CODE REVIEW

**Comment by mgrauer** [comment]
change the version number in setup.py please

**Comment by mgrauer** [comment]
2 comments aside, LGTM.

**Comment by cpatrick** [comment]
Didn't I change the version number in setup.py?

**Comment by mgrauer** [comment]
> Didn't I change the version number in setup.py?

You did indeed.  I didn't scroll down far enough. :sleeping:

**Comment by cpatrick** [comment]
Once Travis and Appveyor is happy, I'll merge.

**Comment by cpatrick** [comment]
(and deploy to pypi)

**Pull request merged**
