### PR TITLE
perform_upload: Do not force revision to 'head' if not specified

### PR DESCRIPTION
**Pull request by jcfr**
This commit update logic to conforms with the feature documented here
and implemented on the server side. It basically allows new revision to
be created when uploading data in an item that already has a revision.

### CODE REVIEW

**Comment by jamiesnape** [comment]
It may or may not be ideal, but the previous behavior is relied on by at least one large Midas Server instance of which I am aware. I am reticent to have it change unless there is a compelling reason.

**Comment by cpatrick** [comment]
I would favor a new function call for the new behavior.

**Comment by jamiesnape** [comment]
I think that would be sensible.

**Comment by jcfr** [comment]
Makes sense.

What about:
* adding a new parameter named: `create_additional_revision` that would default to `False` to keep the current behaviour.
* updating the documentation accordingly.

The documentation would then be:

```
:param item_id: (optional) If set, will append item ``bitstreams`` to the latest revision 
(or the one set using :param:`revision` ) of the existing item.
:type item_id: int | long
```

```
:param create_additional_revision: (optional) If set, will create a new revision in the 
existing item.
:type create_additional_revision: bool | int | string
```

**Comment by cpatrick** [comment]
That works.

-Patrick

**Comment by jcfr** [comment]
@jamiesnape @cpatrick I updated the PR based on our last discussion.

To illustrate, if for example we consider an item named `helixMask3Labels.nrrd` having 1 revision and one bitstream also named `helixMask3Labels.nrrd`:

* By default, using `perform_upload()` will work as it use to be, it means new bitstream will be added to the existing revision of the item. For example, uploading a file named 'CMakeLists.txt' will result in a new bitstream added to the revision 1:

pydas-pr27_default

* If the parameter `create_additional_revision=True` is specified, a new revision will be created instead:

pydas-pr27-create_additional_revision


Associated code:

```
%reload_ext autoreload
%autoreload 1

# XXX Modified version of PyDas is used.
#     PR submitted: https://github.com/midasplatform/pydas/pull/27
%aimport pydas

import hashlib
import os

midas_url = 'http://slicer.kitware.com/midas3'
email = os.environ["MIDAS_PACKAGE_EMAIL"]
apikey = os.environ["MIDAS_PACKAGE_API_KEY"]
communicator = pydas.core.Communicator(midas_url)

def token(email, apikey):
    return communicator.login_with_api_key(email, apikey)

def md5(fname):
    hash = hashlib.md5()
    with open(fname) as f:
        for chunk in iter(lambda: f.read(4096), ""):
            hash.update(chunk)
    return hash.hexdigest()

def upload_revision(item_id, filepath, create_additional_revision=None):
    checksum = md5(filepath)
    filename = os.path.basename(filepath)
    print("=> md5(%s): %s" % (filename, checksum))
    upload_token = communicator.generate_upload_token(token(email, apikey), item_id, filename, checksum=checksum)
    try:
        if not create_additional_revision is None:
            communicator.perform_upload(upload_token, filename, item_id=item_id, filepath=filepath, create_additional_revision=create_additional_revision)
        else:
            communicator.perform_upload(upload_token, filename, item_id=item_id, filepath=filepath)
    except pydas.exceptions.ParseError:
        print("=> ignoring ParseError [upload_token: %s - filename:%s - filepath: %s]" % (upload_token, filename, filepath))
    print("Done")


upload_revision(219925, '/home/jcfr/Projects/Slicer/Modules/CLI/N4ITKBiasFieldCorrection/Testing/CMakeLists.txt')
upload_revision(219925, '/home/jcfr/Projects/Slicer/CMakeLists.txt', True)
```

**Comment by jamiesnape** [comment]
LGTM. Merging.

**Comment by jcfr** [comment]
Thanks

**Pull request merged**
